=== Gramash/EpamPractice/input.xsd
<xsd:schema attributeFormDefault="unqualified"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://nure.ua/garmash/SummaryTask3/entity"
            xmlns:tns="http://nure.ua/garmash/SummaryTask3/entity">

    <xsd:element name="Pharmaceuticals">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Medicine" type="tns:Medicine" maxOccurs="unbounded">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>


    <xsd:complexType name="Medicine" mixed="true">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:token"/>
            <xsd:element name="pharm" type="xsd:token"/>
            <xsd:element name="group" type="xsd:token"/>
            <xsd:element name="analogs" type="xsd:token" maxOccurs="unbounded"/>
            <xsd:element name="Versions" type="tns:Versions"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="Versions">
        <xsd:sequence>
            <xsd:element name="Version" type="tns:Version" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Version">
        <xsd:sequence>
            <xsd:element name="drugType" type="xsd:token"/>
            <xsd:element name="pharmAnalog" type="xsd:token"/>
            <xsd:element name="Certificate" type="tns:Certificate"/>
            <xsd:element name="Package" type="tns:Package"/>
            <xsd:element name="dosage" type="xsd:token"/>
        </xsd:sequence>
        <xsd:attribute name="versionNo" type="xsd:int" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="Certificate">
        <xsd:sequence>
            <xsd:element name="certificateNo">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:int">
                        <xsd:minInclusive value="1"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="validationDate" type="xsd:date"/>
            <xsd:element name="validationExpire" type="xsd:date"/>
            <xsd:element name="organisation" type="xsd:token"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="Package">
        <xsd:sequence>
            <xsd:element name="type" type="xsd:token"/>
            <xsd:element name="amount" type="xsd:int"/>
            <xsd:element name="price" type="xsd:double"/>
        </xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== Gramash/EpamPractice/input.xml
<?xml version="1.0" encoding="UTF-8"?>
    <st3:Pharmaceuticals xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xmlns:st3="http://nure.ua/garmash/SummaryTask3/entity"
                         xsi:schemaLocation="http://nure.ua/garmash/SummaryTask3/entity input.xsd">
    <Medicine id="1">
        <name>Metronidazoli</name>
        <pharm>Berlin Chemie</pharm>
        <group>Antibiotics</group>
        <analogs>Metresa</analogs>
        <analogs>Sufer</analogs>
        <Versions>
            <Version versionNo="1">
                <drugType>solution</drugType>
                <pharmAnalog>Berlin Chemie</pharmAnalog>
                <Certificate>
                    <certificateNo>12345</certificateNo>
                    <validationDate>2001-01-01</validationDate>
                    <validationExpire>2011-01-01</validationExpire>
                    <organisation>Organisation Name</organisation>
                </Certificate>
                <Package>
                    <type>package</type>
                    <amount>10</amount>
                    <price>29.95</price>
                </Package>
                <dosage>1 amp 3 times a day intravenous + 200.0 NaCl 0.9%</dosage>
            </Version>
            <Version versionNo="2">
                <drugType>tabs</drugType>
                <pharmAnalog>Darnica</pharmAnalog>
                <Certificate>
                    <certificateNo>234575</certificateNo>
                    <validationDate>2016-02-03</validationDate>
                    <validationExpire>2017-12-31</validationExpire>
                    <organisation>Organisation Name2</organisation>
                </Certificate>
                <Package>
                    <type>package</type>
                    <amount>30</amount>
                    <price>57.00</price>
                </Package>
                <dosage>1 amp 3 times a day intravenous + 200.0 NaCl 0.9%</dosage>
            </Version>
        </Versions>
    </Medicine>
    <Medicine id="2">
        <name>penicillini</name>
        <pharm>Berlin Chemie</pharm>
        <group>Antibiotics</group>
        <analogs>Ampicillini</analogs>
        <Versions>
            <Version versionNo="1">
                <drugType>solution</drugType>
                <pharmAnalog>Berlin Chemie</pharmAnalog>
                <Certificate>
                    <certificateNo>2345</certificateNo>
                    <validationDate>2001-01-01</validationDate>
                    <validationExpire>2011-01-01</validationExpire>
                    <organisation>Organization Name</organisation>
                </Certificate>
                <Package>
                    <type>amp</type>
                    <amount>5</amount>
                    <price>19.95</price>
                </Package>
                <dosage>1 amp 2 times a day intravenous</dosage>
            </Version>
        </Versions>
    </Medicine>
</st3:Pharmaceuticals>
